### ISSUE TITLE
Is it not supporting Mysqli ?

### ISSUE THREAD

**Issue by ahsannajam** [hrshadhin/school-management-system#10]
Showing this error "Function mcrypt_get_iv_size() is deprecated" is it the issue of mysqli?
![image](https://user-images.githubusercontent.com/16335675/32537922-1520dee4-c486-11e7-94ba-99a0018c49a1.png)

**Comment by vdanelia** [comment]
Hello,

Change MySql parametres at: \app\config\local\database.php

**Comment by hrshadhin** [comment]
what is your php version? this project build on Laravel 4. According to your error "Function mcrypt_get_iv_size() is deprecated", i think you run php 7 or later. Because php 7 deprecated that function.

**Comment by ahsannajam** [comment]
is there any easy way to shift this laravel project to newer version of laravel?

**Comment by hrshadhin** [comment]
I haven't try it. You can try to migrate laravel 4.2.x to laravel 5.x. 
https://laravel.com/docs/5.1/upgrade#upgrade-5.0
