### ISSUE TITLE
A problem in backend

### ISSUE THREAD

**Issue by DrTridz** [hrshadhin/school-management-system#101]
**Hello I have a server and I installed the necessary settings**
**OS Centos 7**
**php 7.2.0**
**mysql 10**
**Apache/2.4.39**
**npm 6.11.3**
**node 12.10.0**
**if i run this command (

>  npm install

) this is the output**

`
npm WARN saveError ENOENT: no such file or directory, open '/home/xxxx/public_html/school.xxxx.com/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/xxxx/public_html/school.xxxx.com/package.json'
npm WARN school.xxxx.com No description
npm WARN school.xxxx.com No repository field.
npm WARN school.xxxx.com No README data
npm WARN school.xxxx.com No license field.

added 21 packages from 15 contributors in 0.538s
found 0 vulnerabilities
`
==================================
and if i run this command
(

> npm run backend-prod

)
this is the output error **

`> @ backend-prod /home/xxxx/public_html/school-management-system
> npm run backend-production

> @ backend-production /home/xxxx/public_html/school-management-system
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js

/home/xxxx/public_html/school-management-system/webpack.backend.mix.js:25
        )
        ^

SyntaxError: Unexpected token )
    at NativeCompileCache._moduleCompile (/home/xxxx/public_html/school-management-system/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/xxxx/public_html/school-management-system/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/xxxx/public_html/school-management-system/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/xxxx/public_html/school-management-system/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (/home/xxxx/public_html/school-management-system/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/xxxx/public_html/school-management-system/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/utils/convert-argv.js:116:13)
    at requireConfig (/home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/utils/convert-argv.js:118:6)
    at /home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/utils/convert-argv.js:125:17
    at Array.forEach (native)
    at module.exports (/home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/utils/convert-argv.js:123:15)
    at yargs.parse.err (/home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/xxxx/public_html/school-management-system/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/xxxx/public_html/school-management-system/node_modules/webpack-cli/bin/cli.js:365:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxxx/public_html/school-management-system/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ backend-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T03_18_46_369Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-prod: `npm run backend-production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ backend-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T03_18_46_558Z-debug.log
`

**I wish you help me Thank you**

**Comment by DrTridz** [comment]
`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/xxxx/public_html/mdrsh.bn-s3d.com/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/xxxx/public_html/mdrsh.bn-s3d.com/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T04_29_23_070Z-debug.log
`

**Comment by DrTridz** [comment]
`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/xxxx/public_html/school.xxxx.com/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/xxxx/public_html/school.xxxx.com/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T04_29_23_070Z-debug.log
`

**Comment by hrshadhin** [comment]
try node LTS version 10.

**Comment by DrTridz** [comment]
I will try test thank you

**Comment by DrTridz** [comment]
**Same but with more errors </3** 

**[xxxx@centos  school-management-system]$ node -v
v10.16.3
[xxxx@centos school-management-system]$ npm -v
6.9.0**

`[xxxx@centos school-management-system]$ npm install`

```
> core-js-pure@3.1.4 postinstall /home/xxxx/public_html/school.xxxx.com/school-management-system/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> purifycss-webpack@0.7.0 postinstall /home/xxxx/public_html/school.xxxx.com/school-management-system/node_modules/purifycss-webpack
> node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1303 packages from 624 contributors and audited 20770 packages in 32.72s
found 0 vulnerabilities

```



`[xxxx@centos school-management-system]$ npm run backend-prod `
```
> @ backend-prod /home/xxxx/public_html/school.xxxx.com/school-management-system
> npm run backend-production


> @ backend-production /home/xxxx/public_html/school.xxxx.com/school-management-system
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ backend-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T05_47_13_292Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-prod: `npm run backend-production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ backend-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T05_47_16_003Z-debug.log
```


`[xxxx@centos school-management-system]$ npm run frontend-prod `
```
> @ frontend-prod /home/xxxx/public_html/school.xxxx.com/school-management-system
> npm run frontend-production


> @ frontend-production /home/xxxx/public_html/school.xxxx.com/school-management-system
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.frontend.mix.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ frontend-production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.frontend.mix.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ frontend-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T05_48_09_206Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ frontend-prod: `npm run frontend-production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ frontend-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T05_48_09_274Z-debug.log

```

**Comment by hrshadhin** [comment]
`chmod -R 775 /home/xxxx/public_html/school.xxxx.com/school-management-system/node_modules/`
`npm run backend-prod `

**Comment by DrTridz** [comment]
error still exists </3
do you want i send you login data for the server on the mail ..?
```
> @ backend-production /home/xxxx/public_html/school.xxxx.com/school-management-system
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ backend-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T06_59_41_043Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-prod: `npm run backend-production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ backend-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.npm/_logs/2019-09-15T06_59_41_138Z-debug.log

```

**Comment by hrshadhin** [comment]
if you want. then...

**Comment by DrTridz** [comment]
ok do I send it here hello@hrshadhin.me ..?

**Comment by hrshadhin** [comment]
> ok do I send it here [hello@hrshadhin.me](mailto:hello@hrshadhin.me) ..?

ok.

**Comment by DrTridz** [comment]
Thank you for everything

**Comment by jimacoff** [comment]
how this issue solved, the error is still pop up,

**Comment by hrshadhin** [comment]
`code ELIFECYCLE` error through by node on variety of reason. Common reasons are

- Low memory(RAM)
- Swap is not configure
- Bad permission on node_modules directory

**Comment by jimacoff** [comment]
> 
> 
> `code ELIFECYCLE` error through by node on variety of reason. Common reasons are
> 
>     * Low memory(RAM)
> 
>     * Swap is not configure
> 
>     * Bad permission on node_modules directory

thanks for respond, most of this error is on production which server you have use to test this code.
i have use heroku, fastcomet then cloudeway, this error is not solve yet on all this server

**Comment by hrshadhin** [comment]
> > `code ELIFECYCLE` error through by node on variety of reason. Common reasons are
> > ```
> > * Low memory(RAM)
> > 
> > * Swap is not configure
> > 
> > * Bad permission on node_modules directory
> > ```
> 
> thanks for respond, most of this error is on production which server you have use to test this code.
> i have use heroku, fastcomet then cloudeway, this error is not solve yet on all this server

errors like this one is related to Servers, not application code. So don't make this issue long anymore. I would suggest if you don't have access to the server like(cpanel, all PASS[heroku,openshift, ....etc]) then build you assets js,css on local machine and upload it.
