### ISSUE TITLE
I cant Install Your Script on Xampp

### ISSUE THREAD

**Issue by robinbdt453** [hrshadhin/school-management-system#103]
Hello Sir, I cant Install Your Script on Xampp please help please send me a installation Video link or full instruction text file sir please please my mail address:- nahidkazi937@gmail.com

**Comment by hrshadhin** [comment]
Project  readme has full installation guide. You must first setup php development environment on windows.   you can google it or follow this link https://dev.to/alchermd/simple-laravel-setup-for-windows-2kna
