### ISSUE TITLE
ReferenceError: GoogleAnaylytics is not defined

### ISSUE THREAD

**Issue by felix2056** [hrshadhin/school-management-system#108]
I am getting this error after I put my services.json key.
The chart is not working

Edit: I found out that the error was coming from the module import 'chart.js' in the site-dashboard.js file.
Here is the error: SyntaxError: import declarations may only appear at top level of a module
please where is the chart.js file located?

**Comment by hrshadhin** [comment]
Paste full error trace here.

**Comment by felix2056** [comment]
It can't find the module chart.js in the site-dashboard.js

It's retrieving the data but the charts are not displaying

**Comment by hrshadhin** [comment]
https://github.com/hrshadhin/school-management-system/blob/master/resources/assets/backend/js/site-dashboard.js#L1
