### ISSUE TITLE
401 error on many pages using admin/demo123

### ISSUE THREAD

**Issue by alinawaz254** [hrshadhin/school-management-system#111]
Hello,

I recently cloned and configured school-management-system on my localhost and it worked fine.

But giving 401 on many pages using admin/demo123 (Admin) :
/dashboard
/profile
/logout
/lock
/notification/unread

Receiving 401 on following pages using lelah.skiles/demo123 (Teacher) :
/dashboard
/profile
/change-password (this is working fine from admin account)
/logout
/lock
/notification/unread

Receiving 500 errors on:
/site/about-content

Tried to debug myself, but couldn't. The roles and permissions are properly assigned to admin user, but still same error. Checked PermissionMiddleware.php but still no luck.

Please help!!

**Comment by hrshadhin** [comment]
did you clear the application cache? `php artisan cache:clear`

**Comment by alinawaz254** [comment]
Yes, already did.

**Comment by alinawaz254** [comment]
Also, is it open source? If yes, then why there is restriction on changing code in even view files?

If I change anything in the footer section of the admin panel, it gives me CRV error. In other comments you have mentioned that this error occurred when file is corrupt. But actually, when a file is modified, this error shows.

So again my question, is this open source or a personal project?

**Comment by hrshadhin** [comment]
> Yes, already did.

Then it should be other issue. You need to debug it. Debug `permission middleware`

**Comment by hrshadhin** [comment]
> Also, is it open source? If yes, then why there is restriction on changing code in even view files?
> 
> If I change anything in the footer section of the admin panel, it gives me CRV error. In other comments you have mentioned that this error occurred when file is corrupt. But actually, when a file is modified, this error shows.
> 
> So again my question, is this open source or a personal project?

Project is release under AGPL 3.0 its a free(As in freedom) and opensource license.
2nd point why do you need to change footer? I put a protection for those people who doesn't want to give free/open source credit for it.

**Comment by alinawaz254** [comment]
Okay got it. Need to use some other open source.

Thanks anyway!!
