### ISSUE TITLE
Backend about us

### ISSUE THREAD

**Issue by armstrong19877** [hrshadhin/school-management-system#112]
The admin cannot enter or edit the about us of the school. Pls  I will  like a little help on this because it     keeps showing 500
 Oops! Something went wrong.
We will work on fixing that right away.
Meanwhile, you may return to home.
Pls I will seriously appreciate it if this can be resolved for me . Thank you.

**Comment by hrshadhin** [comment]
hi, sorry for late replay. Could you please check debug trace that where is the problem. Or paste the error trace here. I checked it all fine here.
