### ISSUE TITLE
i want to change the footer menu.

### ISSUE THREAD

**Issue by prakeshda** [hrshadhin/school-management-system#114]
Hi i am fresh to laravel i want to develop school management,so i choose your project ,i am unable to change the footer menu, if i change i get (CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]) this error.so please help me to solve this problem asap.

**Comment by hrshadhin** [comment]
May i know which thing in footer, you want to change?

**Comment by prakeshda** [comment]
School Management System v2.0 - cc4a289 || Developed by ShanixLab.this one in the right last end

**Comment by hrshadhin** [comment]
Why? you are using Free(Free as in freedom)/Open source software. So, you should give some credit for this that works righ!

**Comment by prakeshda** [comment]
yes, your are right.But i want to remove that one.

**Comment by hrshadhin** [comment]
If you remove that line. Then how you give credit for this work? can you explain it.
