### ISSUE TITLE
If default academic year is changed, students are not shown

### ISSUE THREAD

**Issue by borjapazr** [hrshadhin/school-management-system#115]
Students should be allowed to reuse to assign them to other academic years. How do you change an existing student to another academic year? Can students already created for other academic years be reused? If the option already exists, where is it?

Thank you.

**Comment by hrshadhin** [comment]
That option is not develop yet for CE.

**Comment by borjapazr** [comment]
And for EE?

**Comment by hrshadhin** [comment]
Yah for EE its has promotion feature. you can see it on demo.

**Comment by borjapazr** [comment]
Oh, I'd love to see it. What menu is it on? Can you share me the direct link? I can't find it.

Thanks.

**Comment by hrshadhin** [comment]
http://cloudschoolbd.com/login 
For promotion http://cloudschoolbd.com/promotion
If you not promote students and change academic year. then those students are not show on any features/menus except reports menu.
