### ISSUE TITLE
unable to add new tab in sidebar

### ISSUE THREAD

**Issue by prakeshda** [hrshadhin/school-management-system#116]
i want to add some more columns in sidebar and assign some extra class.but i add route iam getting 404 error.
i had blade,controller and route the view but it get error

**Comment by hrshadhin** [comment]
Re-check you routes code is it properly written. If all okay then clear route cache `php artisan route:clear` and try again.

**Comment by kilonzoally** [comment]
fail to find location file contained code when i login as a teacher or student,those link on sidebar are domant. i want to edit on code env folder..

**Comment by hrshadhin** [comment]
@kilonzoally `/resources/views/backend/partial/leftsidebar.blade.php`
