### ISSUE TITLE
Database not installing what should i do?

### ISSUE THREAD

**Issue by ahsannajam** [hrshadhin/school-management-system#12]
i m trying to install the database it is showing this error. when i "php artisan migrate"
[PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

migrate [--bench [BENCH]] [--database [DATABASE]] [--force] [--path [PATH]] [--package [PACKAGE]] [--pretend] [--seed]

**Comment by hrshadhin** [comment]
change database setting in "app/config/local/database.php".

**Comment by ahsannajam** [comment]
i changed user name: 'root' , pass: '' and database: 'school' the same name database i created in phpmyadmin still showing
