### ISSUE TITLE
Error : The Mix manifest does not exist

### ISSUE THREAD

**Issue by digiapps** [hrshadhin/school-management-system#122]
Hello ,

I am getting bellow error after installation

The Mix manifest does not exist. (View: C:\xampp\htdocs\school-management-system\resources\views\backend\layouts\front_master.blade.php) (View: C:\xampp\htdocs\school-management-system\resources\views\backend\layouts\front_master.blade.php)

**Comment by hrshadhin** [comment]
Do the following step by step from here https://github.com/hrshadhin/school-management-system#installation-and-use

**Comment by digiapps** [comment]
I followed same will server required node js for this script?

**Comment by hrshadhin** [comment]
If you followed and read carefully then, the problem will be solved then. Read every line by line from here!!! https://github.com/hrshadhin/school-management-system#installation-and-use

**Comment by digiapps** [comment]
Hi, Have you created this for single school.  What if I have to add multiple school?

**Comment by hrshadhin** [comment]
yah. For multiple school you have to install another instance of the app.

**Comment by digiapps** [comment]
Where is that?

**Comment by digiapps** [comment]
Hi 

I am unable to select date in Academic section In given screen shot

getting below error in console
Uncaught TypeError: daysOfWeekDisabled() expects an array parameter
    at Object.u.daysOfWeekDisabled (bootstrap-datetimepicker.min.js:1)
    at Number.<anonymous> (bootstrap-datetimepicker.min.js:1)
    at Function.each (jquery.js:373)
    at Object.u.options (bootstrap-datetimepicker.min.js:1)
    at n (bootstrap-datetimepicker.min.js:2)
    at HTMLInputElement.<anonymous> (bootstrap-datetimepicker.min.js:2)
    at Function.each (jquery.js:367)
    at EVdn.T.fn.init.each (jquery.js:202)
    at EVdn.T.fn.init.e.fn.datetimepicker (bootstrap-datetimepicker.min.js:2)
    at Function.value (Generic.js:55)

![image](https://user-images.githubusercontent.com/8210369/79577890-4a5a0380-807a-11ea-9d58-036af0126b18.png)

**Comment by digiapps** [comment]
Hi, any update how to fix this issue

**Comment by hrshadhin** [comment]
Its a js library update issue. need time to debug and fixed. Keep eye on this #123 . I will fixed it and pushed latest code.

**Comment by digiapps** [comment]
Roles are not editable check boxes shows once page load and then disabled in a second.

![image](https://user-images.githubusercontent.com/8210369/79684745-8c08bc80-81e8-11ea-836d-6e2acb77b37b.png)
