### ISSUE TITLE
401 access denied for new menu/url

### ISSUE THREAD

**Issue by digiapps** [hrshadhin/school-management-system#124]
Hi,

I created a new module Account and created permission for same in permission table and mapped its id in role_permission table but when I am trying to access this page from browser its showing 401  Access denied. Could you please let me help how to add new permission for admin role.

**Comment by digiapps** [comment]
Bellow in screenshot I have added two permission for Admin Only

![image](https://user-images.githubusercontent.com/8210369/79743164-f5580080-82b8-11ea-8b23-c6819d6483ae.png)

**Comment by hrshadhin** [comment]
clear application cache. `php artisan cache:clear`

**Comment by digiapps** [comment]
What detail would be in student account? I created a student account from admin and assigned class section him but after login from student account nothing showing.

**Comment by digiapps** [comment]
![image](https://user-images.githubusercontent.com/8210369/79948672-eaa49380-8491-11ea-99a4-aab2e9bd7e0b.png)
only these 4 menu showing in which clicking academic doesn't act and when clicking on Report its open sub menu student, HRM, marks  and result all with 401 access denied page.

How to access only loggedin student information in his account

**Comment by digiapps** [comment]
> clear application cache. `php artisan cache:clear`

I solved cache issue of permission using php artisan cache:forget spatie.permission.cache

Please let me know how to solve other issue in student account.

**Comment by hrshadhin** [comment]
login with 'admin' user, go to roles and set student role permission there. and get back to student account and check those menus. 

Right now student account access very view resources. i.e: view his subjects, section, marks, payments, attendance etc.

**Comment by digiapps** [comment]
From where I can create payment

**Comment by digiapps** [comment]
From where I can create payment?
