### ISSUE TITLE
401 Access denied

### ISSUE THREAD

**Issue by msalmanali0683** [hrshadhin/school-management-system#125]
error 401 is found when the admi  login on every page
![image](https://user-images.githubusercontent.com/45806776/79947591-a3b39f80-848b-11ea-836d-72137f542132.png)

**Comment by hrshadhin** [comment]
My i know you produce that error? and `frontend/home` where did you get this url?

**Comment by msalmanali0683** [comment]
Sir when i logged in the system through username and password which you have provide below the project than this error is showing
in the database i have give the permisions and roles but same error is showing

**Comment by msalmanali0683** [comment]
Sir on every page this error is occuring
![image](https://user-images.githubusercontent.com/45806776/79947591-a3b39f80-848b-11ea-836d-72137f542132.png)

**Comment by hrshadhin** [comment]
clear application cache. ` php artisan cache:clear`
and also don't run Laravel project like other php project by visiting: `localhost/xxxx/zzzz/etc`
that will caused unexpected errors. use laravel development server.
