### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by charisma2** [hrshadhin/school-management-system#127]
I am having the following message when I try to migrate the artisan?

c:\xampp\htdocs\school-management-system-master>php artisan migrate
PHP Warning:  require(C:\xampp\htdocs\school-management-system-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\school-management-system-master\artisan on line 18
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\school-management-system-master/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\xampp\htdocs\school-management-system-master\artisan on line 18

**Comment by hrshadhin** [comment]
https://github.com/hrshadhin/school-management-system#installation-and-use
