### ISSUE TITLE
Localhost it's working fine but unable to setup in cpanel need help

### ISSUE THREAD

**Issue by Toheed16** [hrshadhin/school-management-system#128]
Localhost it's working fine but unable to setup in cpanel need help

**Comment by hrshadhin** [comment]
please post the error trace here, so we can investigate that.

**Comment by Toheed16** [comment]
i'm running on xampp after run the php artisan serve cmd it's running fine on localhost:8000 but on the hosting i import all the data there and then i execute the cmd on terminal but it's icons not showing seems like something is not running and also please let me know how i set path from localhost:8000 to my domain.com ?

**Comment by hrshadhin** [comment]
You are mixing local development server run comand and cpanel hosting process. First study about how to host laravel application on shared hosting.

**Comment by Toheed16** [comment]
Thanks for your reply after learning laravel steps then i hosted this on
cpanel it's working fine but it's icons not showing can you please take a
look at it test link is below please look at it.
https://test.toheedqamar.com/public/

Waiting your response on this,
Thanks for your time.

**Comment by Toheed16** [comment]
All issues solved.

**Comment by hrshadhin** [comment]
what was the problem?

**Comment by Toheed16** [comment]
basically cpanel settings is different then pc and vps so that's why there is some complexity to setting up on different platforms but i solve the issued with the help of some articles related to each platforms thanks for your help Hrshadhin.
