### ISSUE TITLE
Creating Database Issue

### ISSUE THREAD

**Issue by ahsannajam** [hrshadhin/school-management-system#13]
i changed in database.php files-> username: 'root' , pass: '' and database: 'school' the same name database i created in phpmyadmin but still showing error
[PDOException]
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

migrate [--bench [BENCH]] [--database [DATABASE]] [--force] [--path [PATH]] [--package [PACKAGE]] [--pretend] [--seed]

**Comment by hrshadhin** [comment]
set root user password. Don't leave it blank ""!
