### ISSUE TITLE
Error when adding new student attendance 

### ISSUE THREAD

**Issue by Siberon** [hrshadhin/school-management-system#130]
![Capture](https://user-images.githubusercontent.com/46264859/81964558-f0306c00-9640-11ea-9453-3c11aa142fb0.PNG)

**Comment by hrshadhin** [comment]
set `debug=true` in `.env` file and retry. Check the error trace. Or paste the error trace here.

**Comment by Siberon** [comment]
Sorry. I've set it to true but can you tell me where to check the error trace?

**Comment by hrshadhin** [comment]
after you set `debug=true` and add attendance then when error occurs you should get a error page that has full error trace and details about the errors.

**Comment by Siberon** [comment]
![1](https://user-images.githubusercontent.com/46264859/82216335-08570280-9943-11ea-835c-37084fe41ee6.PNG)
Is it this one? I set it to true but I don't see any error trace and details
![image](https://user-images.githubusercontent.com/46264859/82217475-aa2b1f00-9944-11ea-8a98-b882d10be3df.png)

**Comment by Siberon** [comment]
nevermind. After I download and import new releases. I can see it
![image](https://user-images.githubusercontent.com/46264859/82218763-92549a80-9946-11ea-927e-b2eadad19ffc.png)
Can you select the one I need to copy it to here

**Comment by Siberon** [comment]
The error is because my php version is higher so to fix it. I recommend watch tutorial how to downgrade your php version to 7.1.3
