### ISSUE TITLE
About us error in Site-Home-About us(Backend)

### ISSUE THREAD

**Issue by Siberon** [hrshadhin/school-management-system#132]
![image](https://user-images.githubusercontent.com/46264859/82219450-80272c00-9947-11ea-8718-89b91809a58a.png)

**Comment by hrshadhin** [comment]
which php version you are using?

**Comment by Siberon** [comment]
![image](https://user-images.githubusercontent.com/46264859/82301074-f0828b80-99e1-11ea-9ae0-d14f30acc337.png)

**Comment by hrshadhin** [comment]
h. i see. i will push the fixed soon. Or in the meanwhile you can try to use php 7.1 or 7.2

**Comment by Siberon** [comment]
Can I know which version php is the most updated that I can use?

**Comment by Siberon** [comment]
Thank you
