### ISSUE TITLE
Header & Footer (Contact Us want to change)

### ISSUE THREAD

**Issue by Siberon** [hrshadhin/school-management-system#133]
How to change the value of this contact us?

![image](https://user-images.githubusercontent.com/46264859/82378784-fc0c9b80-9a4f-11ea-8e88-26f879c3ce21.png)
![image](https://user-images.githubusercontent.com/46264859/82378797-02027c80-9a50-11ea-9d9f-83774d1ccad3.png)

**Comment by Siberon** [comment]
I changed it already by update data. and redo the instruction of how to load demo data, clear cache, run front-end prod. but all my settings changed to default. Do you know why? what steps should I use instead? [image](https://user-images.githubusercontent.com/46264859/82380753-3166b880-9a53-11ea-9084-62c5ad69e839.png)

**Comment by hrshadhin** [comment]
to update information use application settings menu. after you change that frontend website will automatically reflect the changes. If you change in demo data setup then after you seed the data you have to clear the cache.
