### ISSUE TITLE
Is enterprise edition available on private server for a school?

### ISSUE THREAD

**Issue by edugrip** [hrshadhin/school-management-system#134]

**Comment by hrshadhin** [comment]
For enterprise edition, you have to buy a copy of full source code. Any further details join our discord channel https://discord.gg/7rXyuu8 or email me dev[**at**]hrshadhin[**dot**]me

**Comment by edugrip** [comment]
what is the price for full source code.

**Comment by hrshadhin** [comment]
For that you have to send private message. Check previous message there for details.
