### ISSUE TITLE
Print Reports Issues or not (?)

### ISSUE THREAD

**Issue by Siberon** [hrshadhin/school-management-system#135]
When I print reports. it showed up briefly (<1sec) before closing after that. I can not view it again. There's no error so can you let me know what could possibly be the problem? I'm using google chrome and xampp

Update: The issues only appear in my google chrome. When I'm using Microsoft Edge. The print did showed up.

**Comment by hrshadhin** [comment]
That was the browser print windows issue. i will the fixed this week with latest version of the app.

**Comment by Siberon** [comment]
Okay thanks!

**Comment by RayhanYulanda** [comment]
Still waiting for this issue @hrshadhin

**Comment by RayhanYulanda** [comment]
This issue should be open

**Comment by hrshadhin** [comment]
issue has been fixed with latest release 3.0.0

**Comment by RayhanYulanda** [comment]
Thanks a lott ❤  @hrshadhin
