### ISSUE TITLE
Can i upload it to web hosting?

### ISSUE THREAD

**Issue by ahsannajam** [hrshadhin/school-management-system#14]
What should i change to run if i upload this project to my web hosting? what should i replace in local/database.php file?

**Comment by hrshadhin** [comment]
no. you have to change app/config/database.php. Not local one. and also change app debug to false.
Then change toggle true and false here and change url also.
https://github.com/hrshadhin/school-management-system/blob/master/bootstrap/start.php#L27

**Comment by ahsannajam** [comment]
i changed debug to false in  config/app.php, created database and changed credentials in app/config/database.php and url in 'app/config/app.php' what should i change else? thanks
