### ISSUE TITLE
Vendor file missing error

### ISSUE THREAD

**Issue by mwaqas246** [hrshadhin/school-management-system#15]
Hi, 
When I run this project and got vendor files issue, that's missing in this project. Need to fix

**Comment by hrshadhin** [comment]
Run `composer install`.
fllow the installation instruction carefully
https://github.com/hrshadhin/school-management-system#sms-is-build-using-laravel-42

**Comment by mwaqas246** [comment]
I tried as you said and got this error
C:\xampp\htdocs\lar> php artisan migrate
PHP Warning:  require(C:\xampp\htdocs\lar\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\lar\bootstrap\autoload.php on line 17

Warning: require(C:\xampp\htdocs\lar\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\lar\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\lar\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\lar\bootstrap\autoload.php on line 17

**Comment by hrshadhin** [comment]
Before ` php artisan migrate` run `composer install`. I think your "composer install" not done properly.

**Comment by aashu122** [comment]
> Before ` php artisan migrate` run `composer install`. I think your "composer install" not done properly.

I have also facing this problem and tell me whats the use composer of this erp and that iss the incorrect commond of composer.and tell i can find autoload.php file
