### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by anthonybocci** [hrshadhin/school-management-system#16]
Hi,
It seems the project is not compatible with PHP 7.2.
The problem is Laravel 4 is using _MCrypt_ extension, that was removed in PHP 7.2.

I suggest to port the project to Laravel 5 and PHP 7.2.

**Comment by hrshadhin** [comment]
Yah, i know it. I have a plan to migrate this project to Laravel 5 and also php 7 compatible. End of this month i will do it.
