### ISSUE TITLE
Student Attendence return 500 error

### ISSUE THREAD

**Issue by DikshantNiraula** [hrshadhin/school-management-system#162]
I dont know the reason but it returns 500 error page after installing
Others things are all right

**Comment by DikshantNiraula** [comment]
when I try to create student attendance it returns 500 page

**Comment by hrshadhin** [comment]
set `debug=true` in `.env` and check what is the problem and paste the error here.

**Comment by DikshantNiraula** [comment]
Its Solved already,
I did that already and Error was due to one variable was sent to view without defining it...SO I close this issue here...
By the way Cool App this is..

**Comment by foyzul86** [comment]
Please share details with us. Like which variable... Or send file pls foyzul86@gmail.com

**Comment by foyzul86** [comment]
> Its Solved already, I did that already and Error was due to one variable was sent to view without defining it...SO I close this issue here... By the way Cool App this is..

Please share details with us. Like which variable... Or send file pls foyzul86@gmail.com
