### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by usmanbasharmal123** [hrshadhin/school-management-system#163]
**Describe the bug**
I have installed the project as per your video but when I try to access it via PHP artisan serve it shows me the below error 

I have run composer update,npm install 

**Expected behavior**

Laravel development server started: http://127.0.0.1:8000

[Sat Mar 20 07:39:08 2021] PHP Fatal error:  Uncaught Exception: The Mix manifest does not exist. in C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Foundation\Mix.php:46
Stack trace:
#0 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(574): Illuminate\Foundation\Mix->__invoke('/css/vendor.css')
#1 C:\xampp\htdocs\cms\storage\framework\views\580789b0ee664e84af41fdd693c824555761f7a0.php(14): mix('/css/vendor.css')       
#2 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\cms\vendor\facade\ignition\src\Views\Engines\CompilerEngine.php(36): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\View\View.php(143): Facade\Ignition\Views\Engines\CompilerEngine->get('C:\ in C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Foundation\Mix.php on line 46
[Sat Mar 20 07:39:08 2021] PHP Fatal error:  Uncaught Exception: The Mix manifest does not exist. in C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Foundation\Mix.php:46
Stack trace:
#0 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(574): Illuminate\Foundation\Mix->__invoke('/css/vendor.css')
#1 C:\xampp\htdocs\cms\storage\framework\views\580789b0ee664e84af41fdd693c824555761f7a0.php(14): mix('/css/vendor.css')
#2 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#4 C:\xampp\htdocs\cms\vendor\facade\ignition\src\Views\Engines\CompilerEngine.php(36): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\View\View.php(143): Facade\Ignition\Views\Engines\CompilerEngine->get('C:\ in C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Foundation\Mix.php on line 46

**Screenshots**

**Comment by hrshadhin** [comment]
we don't have any installation video for this project. Which reference you are referring? Follow installation guide line by line that have here with this repository first.

**Comment by usmanbasharmal123** [comment]
Sorry for the inconvenience and thanks for the prompt response, I follow the instruction and it worked  Thanks again
