### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by 06fitreeyru** [hrshadhin/school-management-system#175]
Academic ---> class not add
subject not add

error 500 Oops! Something went wrong.

**Comment by 06fitreeyru** [comment]
![image](https://user-images.githubusercontent.com/80571649/123294783-5a535a00-d53f-11eb-8191-a1f281e620ab.png)

**Comment by 06fitreeyru** [comment]
![image](https://user-images.githubusercontent.com/80571649/123308967-875b3900-d54e-11eb-857c-7e26aaf67634.png)
Teachers cannot add marks for their own Subject.

**Comment by hrshadhin** [comment]
Turn on debug `true` in `.env` and check the log, what's generating the error. 
And before post your issue, please follow issue report template. That's help to reproduce the error.

**Comment by 06fitreeyru** [comment]
I added a new file named timetable in the Academic/Subject folder. But when I become a student, teacher, or something that is not an admin, it shows error 401 Unauthorized, where should I fix it? to allow other roles to access the page.

![image](https://user-images.githubusercontent.com/80571649/127762519-6ad4e2c8-02f6-46a7-8432-fddf5798e724.png)
