### ISSUE TITLE
Not displaying pictures after uploading new images on live server

### ISSUE THREAD

**Issue by bngalande** [hrshadhin/school-management-system#178]
**Not displaying image after uploading**
I uploaded new images to the site gallery but the image are not showing

![Screenshot_20210728-191757](https://user-images.githubusercontent.com/79098581/127368041-60ac0106-7959-4105-9476-364aa7fbb5e3.png)

**Comment by hrshadhin** [comment]
run `php artisan storage:link` command & refresh browser.

**Comment by bngalande** [comment]
It is says public/storage already exists after running that command
![Screenshot_20210809-123820](https://user-images.githubusercontent.com/79098581/128694375-0fa575fb-e62b-469e-a77f-539156db2a8c.png)

**Comment by hrshadhin** [comment]
remove the directory before run the command.

**Comment by bngalande** [comment]
I deleted the directory and ran the command and a new storage directory was created but the problem wasn't fixed

**Comment by hrshadhin** [comment]
ok. check `storage/app/public/` directory that file actually uploaded or not. Also turn-on debug mode while uploading the image and check is there have any permission error.

**Comment by bngalande** [comment]
Yes the image is uploaded but it doesn't look like a valid image file and the name is more like encrypted
![Screenshot_20210816-220807](https://user-images.githubusercontent.com/79098581/129623556-e9e4cf87-405e-487c-afd2-a29acfceb845.png)

**Comment by hrshadhin** [comment]
image name is ok, it's not encrypted. you are right may be your image is corrupted. Could you try
`.png` or `.jpg` image.

**Comment by bngalande** [comment]
I tried both .png and .jpg files but same issue
