### ISSUE TITLE
Student Attendance Error

### ISSUE THREAD

**Issue by bngalande** [hrshadhin/school-management-system#179]
I installed the application correctly by following the steps you outlined and I was testing the modules but the add student function is bringing an error. I have already enabled debug mode and I have attached the error detail. How can I resolve this issue.
![Screenshot_20210729-101054](https://user-images.githubusercontent.com/79098581/127456228-da2d8d51-2d2e-4d53-8737-98cdedbfc6e2.png)

**Comment by hrshadhin** [comment]
remove `sections` variable. And please follow issue template before posting your issue.
To debug your issue we must need those details.
