### ISSUE TITLE
License Update for Network

### ISSUE THREAD

**Issue by changeweb** [hrshadhin/school-management-system#18]
This software has to run over a network to work. According to [GNU License Project](https://www.gnu.org/licenses/licenses.html) any software which will commonly be run over a network should consider using the GNU AGPL. So License of this software should be based on AGPL v3 instead of GPL v3.

**Comment by hrshadhin** [comment]
Thanks for your suggetion. But you didn't clearify why should i use that? 
Here is the reason:
> Using the GNU Affero GPL avoids that outcome. If D runs his version on a server that everyone can use, you too can use it. Assuming he has followed the license requirement to let the server's users download the source code of his version, you can do so, and then you can incorporate his changes into your version. (If he hasn't followed it, you have your lawyer complain to him.)
[https://www.gnu.org/licenses/why-affero-gpl.en.html](url)
