### ISSUE TITLE
Question request

### ISSUE THREAD

**Issue by 06fitreeyru** [hrshadhin/school-management-system#180]
I added a new file named timetable in the Academic/Subject folder. But when I become a student, teacher, or something that is not an admin, it shows error 401 Unauthorized, where should I fix it? to allow other roles to access the page.

![image](https://user-images.githubusercontent.com/80571649/127762519-6ad4e2c8-02f6-46a7-8432-fddf5798e724.png)

**Comment by hrshadhin** [comment]
After you create any menu/route. you have to add this route to permission table. or add [here](https://github.com/hrshadhin/school-management-system/blob/master/database/seeds/PermissionTableSeeder.php) and run seed command. 

After that go to role menu and assign this permission to desire role.
