### ISSUE TITLE
cloudSchool Installation - PHP version error

### ISSUE THREAD

**Issue by anthonyaniah** [hrshadhin/school-management-system#182]
Problem 1
    - hrshadhin/laravel-userstamps[v2.0.1, ..., 2.x-dev] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - Root composer.json requires hrshadhin/laravel-userstamps ^2.0.1 -> satisfiable by hrshadhin/laravel-userstamps[v2.0.1, 2.x-dev]

**Comment by anthonyaniah** [comment]
I Later changed the composer.json file requirement to { "php": "^7.2| ^8.0", ... }
but still could not address the problem.

**Comment by hrshadhin** [comment]
That library is not compatible with php 8. you have to use 7.2 for the time being.

**Comment by anthonyaniah** [comment]
Thanks. Regards.
