### ISSUE TITLE
Error 500 when trying to create student attendance

### ISSUE THREAD

**Issue by AllanMwaura22** [hrshadhin/school-management-system#184]
Am getting server error 500 when trying to create student attendance.What could I be doing wrong?
![Screenshot_2021-09-16_11-28-30](https://user-images.githubusercontent.com/42067875/133578924-aac4229f-6016-43ab-bd79-4c2d157c8733.png)

**Comment by AllanMwaura22** [comment]
After enabling debug,I managed to troubleshoot the problem.

**Comment by foyzul86** [comment]
please, describe details how to solve.

**Comment by AllanMwaura22** [comment]
Set your debug to true on .env this will give you an understandable error,post it here.

**Comment by hanu7674** [comment]
First go to the App->Http->Controllers->Backend->StudentAttendanceController.php on line number 200 there is a variable name called sections is there. remove the sections variable then you will view the attendance create page.

**Comment by OmParkashPandeY** [comment]
> First go to the App->Http->Controllers->Backend->StudentAttendanceController.php on line number 200 there is a variable name called sections is there. remove the sections variable then you will view the attendance create page.

Thanks Bro
