### ISSUE TITLE
not able to create database

### ISSUE THREAD

**Issue by raznesh** [hrshadhin/school-management-system#19]
Hi,

I'm getting below, error while we are migrating the DB.

![image](https://user-images.githubusercontent.com/27947637/38194778-476ddfc2-3697-11e8-81ec-01d6f2371766.png)

**Comment by hrshadhin** [comment]
check your db settings first! like username and password.

**Comment by hrshadhin** [comment]
check here which environment is active,
https://github.com/hrshadhin/school-management-system/blob/master/bootstrap/start.php#L27
if its local then you have to change settings for db in this file 
https://github.com/hrshadhin/school-management-system/blob/master/app/config/local/database.php

or if it production then you have to change settings for db in this file 
https://github.com/hrshadhin/school-management-system/blob/master/app/config/database.php

**Comment by raznesh** [comment]
Thank you for support, now I could able to create the database and tables. 

But I'm not able to access the portal, please see below screenshot.

![image](https://user-images.githubusercontent.com/27947637/38317909-c85ec406-384b-11e8-9bdf-6d7b96c7adc7.png)


Please let me know if I'm doing any wrong configuration.

**Comment by hrshadhin** [comment]
What do you mean by not accessing the site? your screenshot is not clear to me. And one thing github issue for report bugs or coding issue. It's not a discussion forum. I you need help email me.
