### ISSUE TITLE
Student Attendance Module not working

### ISSUE THREAD

**Issue by foyzul86** [hrshadhin/school-management-system#191]
1.Attendance
2.Student Attendance
3.Add New Button

Problem: when click on add new button, then show error like below
500
Oops! Something went wrong.

We will work on fixing that right away.
Meanwhile, you may return to home

Please solve the error/problem

Thank you
![attaendance](https://user-images.githubusercontent.com/68741273/147463514-2171819c-365b-44d8-8f55-07dc17131a54.png)

**Comment by hrshadhin** [comment]
please don't re-create same issue again. Share your error logs and details about your environments in here #184
