### ISSUE TITLE
Laravel Version

### ISSUE THREAD

**Issue by vino-jasuba** [hrshadhin/school-management-system#20]
Hello, this isn't an issue per se but I have to raise it just the same. Why are you using Laravel 4.2? 
Also, this might be the wrong place to bring it up but would you like another contributor to move it to 5.6? I'd very much like to be a part of it.

**Comment by vino-jasuba** [comment]
That's great, do you want me to work off of your repo or to make a fork of
it and submit a pull request when I'm done?

**Comment by hrshadhin** [comment]
Which one do you prefer? give me two days i have some updated codes for dynamic marking rules, when i am done with pushed i will tell you.

**Comment by vino-jasuba** [comment]
I'm okay with both approaches so I'll use the one you prefer

**Comment by hrshadhin** [comment]
ok then. after i pushed the latest codes, i will add you as a contributor. Then you create a new branch and migrate the code. And again thank you very much.

**Comment by vino-jasuba** [comment]
That's great! Thank you very much. I'll be waiting for you to push those
updates.

**Comment by vino-jasuba** [comment]
I'm still open to the idea but it'll take me a little longer because I
started work on er project.

**Comment by hrshadhin** [comment]
ok. no problem. When you are free just knock me here `hello[AT]hrshadhin[dot]me`

**Comment by hrshadhin** [comment]
i pushed latest codes here. And laravel version migration and theme upgration is in progress.
