### ISSUE TITLE
Header Section is Missing on Dashboard

### ISSUE THREAD

**Issue by khusroohayat** [hrshadhin/school-management-system#218]
**Describe the bug**
Header Section is Missing on Dashboard, Although it Header Section is showing on rest of pages

**To Reproduce**
1. Go to '[Cloud School](https://demo.cloudschoolbd.com/dashboard)'
2. See the dashboad page
3. Check other pages and see the header [section]

**Expected behavior**

Top Header Should show like rest of pages

**Screenshots**
![firefox_FO21s1p6LM](https://user-images.githubusercontent.com/5275996/179607244-7f1dd69a-7eea-4701-ac6b-09e1f8599753.png)

![firefox_LCbBzpiv63](https://user-images.githubusercontent.com/5275996/179607254-4132616b-1da8-4809-9af5-2ae14267395a.png)

**Desktop (please complete the following information):**
 - Browser - Firefox

**Comment by hrshadhin** [comment]
Your marking area is not header section. That statistic section under dashboard page. That's why statistic section not showing on other page.
