### ISSUE TITLE
Please Upload A Database 

### ISSUE THREAD

**Issue by srkneil** [hrshadhin/school-management-system#22]
Please Upload A Database

**Comment by hrshadhin** [comment]
sorry i can't give schema file. You have to generate it from code. if you have any issue with generate it then i will help.

**Comment by ganeshjogam** [comment]
I am able to generate database but not able to login maybe you can share the .sql data

**Comment by hrshadhin** [comment]
run this command to create a admin user `php artisan db:seed`

**Comment by ganeshjogam** [comment]
I am able to run this command and able to see two records in user table but it is redirecting to login again

**Comment by hrshadhin** [comment]
check folders and files permission again. May be application can't write session, so after login its redirect to login.

**Comment by ganeshjogam** [comment]
How to do on windows any idea
I am getting 
CRV: Application encounted problems.Please contact ShanixLab[hello@hrshadhin.me]

**Comment by ganeshjogam** [comment]
How to reinstall and debug the cause of error
