### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by 133usr** [hrshadhin/school-management-system#235]
I followed all the steps of installation 
However the  app just wont run ..

please help, I also went thru all the issues but I couldn't find mine..

![image](https://user-images.githubusercontent.com/78338503/213617134-c6cb6628-632f-4ed7-9bea-6b68342da2eb.png)

This error keeps coming and when I open the server 

error 500 comes

**Comment by hrshadhin** [comment]
Read the error carefully. It's clearly shows that  your using wrong mysql password.
