### ISSUE TITLE
Parents login?

### ISSUE THREAD

**Issue by 133usr** [hrshadhin/school-management-system#236]
![image](https://user-images.githubusercontent.com/78338503/213914911-d70fa5df-fbcc-431d-ae0e-ee6b01ba1da9.png)

In the image above we can see the Role of parent

But I couldnt' find a way to create an id of parent so that they may see login and access data.

Please help me

**Comment by 133usr** [comment]
I found the way to create a parent but How to assign student to that parent??

**Comment by hrshadhin** [comment]
That is for future scope. currently you can't assign student to parent.

**Comment by 133usr** [comment]
Then what is the purpose of creating parents as a user?
 and assigning them id and pass?

**Comment by 133usr** [comment]
> That is for future scope. currently you can't assign student to parent.


Then what is the purpose of creating parents as a user?
and assigning them id and pass?
Am I missing something??
