### ISSUE TITLE
Willing to Contribute Great Content to the School-Management-System App/Site Homepage

### ISSUE THREAD

**Issue by order4adwriter** [hrshadhin/school-management-system#25]
Hi,

My name is Phil and I am a professional copywriter.

I'd like to contribute to the School-Management-System project by creating informative, captivating and enticing content for the website homepage.

I have done this for many other projects here on GitHub and I believe my copywriting contributions will be immensely beneficial to the School-Management-System Project

In this vein, I'll also be submitting other contributions for the website such as ...
Homepage content
FAQ page content
Wiki content
Press releases/ blog posts
Tutorials on How to use School-Management-System effectively

...and other content as required by the POs.

Such content will undoubtedly improve return traffic to the website and ultimately convince more site visitors to download and install the app, thereby increasing the popularity of the app in the long run.

Now...

Can I go ahead and create the content?

Also, will the contributions be merged to the master repository?

Please let me know asap, so I could get started immediately.

I know that I probably don't need to do this but I believe that getting your permission before going ahead is indeed the right thing to do.

Thanks for taking the time to read this as I readily await your positive response

**Comment by hrshadhin** [comment]
Hi Phil,
Thanks for asking for this. I was planing to write wiki for this project but i'm busy with others projects. 

Can I go ahead and create the content?
>> Yes, you can.
Also, will the contributions be merged to the master repository?
>>  yes.
