### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by shyamkrishnak89** [hrshadhin/school-management-system#28]
Hello,
I have followed the instructions you have given(for local implementation). Migrating done well. When i typed localhost:8000 in browser, I got a fatal error like this. Iam attaching the screenshots of it. Please help me to get out of this error.
![error-2](https://user-images.githubusercontent.com/1607108/41671736-9bae8e0c-74d5-11e8-8601-a0226e739cf4.jpg)

**Comment by hrshadhin** [comment]
Which php version did you tried it on?

**Comment by shyamkrishnak89** [comment]
Tried both 7 and 7.1

**Comment by synectiks-code** [comment]
I get 
![image](https://user-images.githubusercontent.com/30368497/41702823-12e4b158-754f-11e8-8859-d922ec3d78d8.png)

I am using php 7.2
migration was fine , two tables populated

**Comment by hrshadhin** [comment]
@shyamkrishnak89 which branch your are using? if its master or v1.0 then you must use php <= 5.6 or if v2.0-dev then php >= 7.1.3 . I didn't face error like you, i thinks its a xampp php issue. I can't test it on xampp because i don't use windows. So sorry i can't help you with this. You can try new or another version of xampp.

**Comment by hrshadhin** [comment]
@synectiks-code copy the env configuration file
`$ cp .env.example .env`
change your settings and must set the debug "true". Then run the application you will find where is the problem that cause the error.

**Comment by synectiks-code** [comment]
it says
![image](https://user-images.githubusercontent.com/30368497/41727507-234bf27a-7592-11e8-85e8-bcb0d0644850.png)

**Comment by synectiks-code** [comment]
also release or mainline branch does not work with postgresql database.

**Comment by shyamkrishnak89** [comment]
@hrshadhin My issue got solved!!! php 5.6 is needed. Thanks for your help. But there is login issue with USER: admin PASS: demo123
![login error](https://user-images.githubusercontent.com/1607108/41732669-3e806a28-759f-11e8-9b0f-1eebaa781288.jpg)

**Comment by hrshadhin** [comment]
@shyamkrishnak89 reinstall the app, error will be gone i hope.

**Comment by hrshadhin** [comment]
@synectiks-code I strongly recomanded to use mysql or mariadb. Master or v1.0 branch doesn't fully compatible with PGSQL
