### ISSUE TITLE
CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]

### ISSUE THREAD

**Issue by shyamkrishnak89** [hrshadhin/school-management-system#29]
I have installed master with php5.6 locally. Migrating was fine. But getting error like this "CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]" while giving details USER:admin and PASS:demo123. 

I tried to reinstall the app. Still no change.
![image](https://user-images.githubusercontent.com/1607108/41770405-b1f2ce66-762f-11e8-9883-4d9df7e74b23.png)

**Comment by hrshadhin** [comment]
Meaning of this error message is your application files has been corrupted somehow. If you install the app with a fresh copy the, error will be gone.
