### ISSUE TITLE
Not able to download and install on my local system

### ISSUE THREAD

**Issue by josephopio11** [hrshadhin/school-management-system#3]
Can you please make a video tutorial to help is be able to download and install it on our local machines. It failed completely even after following all the directions you gave right here. I spent over 12 hours and kept reinstalling OS thinking it was the issue. I was using centos 7

**Comment by hrshadhin** [comment]
first setup LAMP on your centos 7. then check is php runing. after that host this app on lamp.
If you face any problem then follow laravel installation on LAMP tuts.

**Comment by josephopio11** [comment]
I'll try again in a while and then inform you
