### ISSUE TITLE
Problem in Migration

### ISSUE THREAD

**Issue by theenescresta** [hrshadhin/school-management-system#32]
Thank you for great MIS.
i have a problem in migration would you please help me?
when i run php artisan migrate command then the following error will appears.
[PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

db:seed [--class [CLASS]] [--database [DATABASE]] [--force]

**Comment by hrshadhin** [comment]
Fllow this issue: 
https://github.com/hrshadhin/school-management-system/issues/19
