### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by theenescresta** [hrshadhin/school-management-system#33]
After doing as per issue no 12. Following error appears while migrating 
php artisan migrate

  [ErrorException]
  Undefined index: driver

migrate [--bench [BENCH]] [--database [DATABASE]] [--force] [--path [PATH]] [--package [PACKAGE]] [--pretend] [--seed]

**Comment by hrshadhin** [comment]
recheck your settings. I said to follow issue no 19. Don't create new issue on per question. You can comment to existing issue.
