### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by IsoftTech** [hrshadhin/school-management-system#34]
After cloning the project, I discovered the file does not have composer, view and others. Then I ran composer install this is the error i got:
C:\xampp\htdocs\school-management-system\public>composer install
No composer.json in current directory, do you want to use the one at C:\xampp\htdocs\school-management-system? [Y,n]? y
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for d11wtq/boris v1.0.10 -> satisfiable by d11wtq/boris[v1.0.10].
    - d11wtq/boris v1.0.10 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
  Problem 2
    - d11wtq/boris v1.0.10 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
    - laravel/framework v4.2.22 requires d11wtq/boris ~1.0 -> satisfiable by d11wtq/boris[v1.0.10].
    - Installation request for laravel/framework v4.2.22 -> satisfiable by laravel/framework[v4.2.22].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

C:\xampp\htdocs\school-management-system\public>

Please what is the possible solutions, thanks

**Comment by hrshadhin** [comment]
I think your cloning was not succefully download all file. every branch or this repo has composer.json file. 
For the php extention error. You have to enable "pcntl" extention in php.ini file. I hope issue will be solved.

**Comment by IsoftTech** [comment]
There's no views and composer in version

**Comment by hrshadhin** [comment]
V1.0 or master branch doesn't have .env file. Where did you get that instruction!? Only v2.0-dev use .env file.

**Comment by hguru** [comment]
Use the composer update command, to solve this issue

**Comment by hguru** [comment]
When i tried to login with the admin credentials, this gives me an error CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]

**Comment by hguru** [comment]
sitll having the same issue CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]

**Comment by hguru** [comment]
am using the master branch in the production deployment environment.

**Comment by hguru** [comment]
I think, i just sorted it out. this was due the APP_KEY

**Comment by hrshadhin** [comment]
@hguru sorry for the wrong question. I mean which os environment?

**Comment by hguru** [comment]
had just switch to my cPanel, but still the same error

**Comment by hrshadhin** [comment]
zip the folder "app/views/layouts" and send me over mail. hello[at]hrshadhin[dot]me

**Comment by IsoftTech** [comment]
school-management-system.zip
<https://drive.google.com/file/d/1aBa5u0qHFX9We4fymmPhv2OC62VdZigA/view?usp=drive_web>
Hello!  Habibur this is the folder, thanks

**Comment by hrshadhin** [comment]
give me the plublic link. not protected link man!

**Comment by AdittoAbhi** [comment]
Bro Same Problem Amar O. Kivabe solve korbo?
