### ISSUE TITLE
PDOException error

### ISSUE THREAD

**Issue by IsoftTech** [hrshadhin/school-management-system#36]
After lots of research, I finally found out how to install laravel 4.2 cloned project. But on running "php artisan migrate and composer install preferred dist", I encounter this error:
 [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
queue:work [--queue [QUEUE]] [--daemon] [--delay [DELAY]] [--force] [--memory [MEMORY]] [--sleep [SLEEP]] [--tries [TRIES]] [--] [<connection>]

  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

queue:work [--queue [QUEUE]] [--daemon] [--delay [DELAY]] [--force] [--memory [MEMORY]] [--sleep [SLEEP]] [--tries [TRIES]] [--] [<connection>]

  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

queue:work [--queue [QUEUE]] [--daemon] [--delay [DELAY]] [--force] [--memory [MEMORY]] [--sleep [SLEEP]] [--tries [TRIES]] [--] [<connection>].
I think there's still something I need to figure out please help me. Thanks in advance.

**Comment by hrshadhin** [comment]
Fllow this issue:
#19

**Comment by IsoftTech** [comment]
It still didn't work for me may be you should take a look at my code:

  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using
password: YES)


migrate [--bench [BENCH]] [--database [DATABASE]] [--force] [--path [PATH]]
[--package [PACKAGE]] [--pretend] [--seed]
First I don't have password for my localhost, xampp.
<?php

return array(

    /*

|--------------------------------------------------------------------------
    | PDO Fetch Style

|--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    /*

|--------------------------------------------------------------------------
    | Default Database Connection Name

|--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => 'mysql',

    /*

|--------------------------------------------------------------------------
    | Database Connections

|--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

     'connections' => array(
        'mysql' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'c_school_main',
            'username'  => 'root',
            'password'  => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),
        'pgsql' => array(
            'driver'   => 'pgsql',
            'host'     => 'localhost',
            'database' => 'forge',
            'username' => 'forge',
            'password' => '',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ),
    ),
);
It could be there's extra setting to be made, thanks in advanced

**Comment by hrshadhin** [comment]
Its clear that you have some DB login issue. I said you follow issue #19. If not solved, then definetly its problem with your DB server. Don't make this thread big unless it needed.
