### ISSUE TITLE
I get this error after install 

### ISSUE THREAD

**Issue by gisacc54** [hrshadhin/school-management-system#41]
RuntimeException thrown with message "No application encryption key has been specified."

Stacktrace:
#17 RuntimeException in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:42
#16 Illuminate\Encryption\EncryptionServiceProvider:Illuminate\Encryption\{closure} in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Support\helpers.php:1041
#15 tap in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:46
#14 Illuminate\Encryption\EncryptionServiceProvider:key in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:24
#13 Illuminate\Encryption\EncryptionServiceProvider:Illuminate\Encryption\{closure} in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:764
#12 Illuminate\Container\Container:build in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:646
#11 Illuminate\Container\Container:resolve in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:601
#10 Illuminate\Container\Container:make in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:734
#9 Illuminate\Foundation\Application:make in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:900
#8 Illuminate\Container\Container:resolveClass in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:828
#7 Illuminate\Container\Container:resolveDependencies in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:795
#6 Illuminate\Container\Container:build in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:646
#5 Illuminate\Container\Container:resolve in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Container\Container.php:601
#4 Illuminate\Container\Container:make in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:734
#3 Illuminate\Foundation\Application:make in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:215
#2 Illuminate\Foundation\Http\Kernel:terminateMiddleware in E:\Gracious project\school-management-system\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:189
#1 Illuminate\Foundation\Http\Kernel:terminate in E:\Gracious project\school-management-system\public\index.php:60
#0 require_once in E:\Gracious project\school-management-system\server.php:21

**Comment by hrshadhin** [comment]
Please before asking very beginner question. do some googling first.
