### ISSUE TITLE
Your username/password combination was incorrect.

### ISSUE THREAD

**Issue by DiniMuhd7** [hrshadhin/school-management-system#43]
Hello, i'm getting error whenever i try to login using the login information below.
USER: admin PASS: demo123**
ERROR - **Your username/password combination was incorrect.

Localhost - http://localhost:8000 ** USER: admin PASS: demo123

![screen shot 2018-09-08 at 9 14 11 am](https://user-images.githubusercontent.com/12256599/45251998-9f368380-b347-11e8-9cf2-3538f8f7d561.png)

**Comment by hrshadhin** [comment]
Did you seed the data?

**Comment by Deen-Adam** [comment]
Yes i did. It was when i didn't realized that the password has been changed. Now it works for me using the new password '123456'. Thanks
