### ISSUE TITLE
Cplink

### ISSUE THREAD

**Issue by JohnnKay** [hrshadhin/school-management-system#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Is it possible to get rid of this "School Management System Version 1.0 - {{substr($idc,0,7)}}|| Developed by <a class="cplink" href="http://shanixlab.com">ShanixLab</a>" and still be able to log in?

**Comment by hrshadhin** [comment]
No. [ Read this line what it says](https://github.com/hrshadhin/school-management-system/blob/master/app/views/layouts/footer.blade.php#L6)
