### ISSUE TITLE
unable to run composer install

### ISSUE THREAD

**Issue by support-system** [hrshadhin/school-management-system#45]
when i am trying to run composer install it is showing 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'school.permissions' doesn't exist (SQL: select * from `permissions`)

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'school.permissions' doesn't exist

please help

Mohit Jain

**Comment by hrshadhin** [comment]
i pushed a fixed for this. Now pull the code again and try.
