### ISSUE TITLE
running on port 80

### ISSUE THREAD

**Issue by rahulamalkar** [hrshadhin/school-management-system#46]
Hi there,
i am trying to run the setup in raspberry pi, 
I have done all the steps to install it in raspberry pi.

but i need to run the setup at port 80, for the ease of use,
i used this command : 
php artisan serve --port 80

but its not comming...

can you please help me in this.

**Comment by hrshadhin** [comment]
At first check that, is 80 port is free or used by some other services. if free then run below command.
`php artisan serve --host 0.0.0.0 --port 80`
