### ISSUE TITLE
dompdf error

### ISSUE THREAD

**Issue by srikanthkarini** [hrshadhin/school-management-system#47]
click on print  i had this error and one more thing there is table name problems i got,
 for example in migrations table name is "student" but  web server it asking table name as "Student" then i created another table called "Student" in web server, now two tables are there "student" and "Student" , data stored in "Student" table , but in my local server only one table name "student"
![dompdf](https://user-images.githubusercontent.com/1457657/48392728-83c66b00-e732-11e8-84f7-cd434e9a62d2.jpg)
![dompdf1](https://user-images.githubusercontent.com/1457657/48392729-83c66b00-e732-11e8-900e-e719552b8556.jpg)
![dompdf2](https://user-images.githubusercontent.com/1457657/48393024-db190b00-e733-11e8-8742-2ce675c90cdb.jpg)

**Comment by hrshadhin** [comment]
table name bug will be fixed soon. for dompdf error please check  on dompdf lib issue list.
