### ISSUE TITLE
Many Problem There.

### ISSUE THREAD

**Issue by Powerin10** [hrshadhin/school-management-system#48]
1st problem
![image](https://user-images.githubusercontent.com/10785280/49534282-5614b200-f8eb-11e8-931f-20a23a934125.png)

2nd problem
![image](https://user-images.githubusercontent.com/10785280/49534323-6cbb0900-f8eb-11e8-97b7-4307e9206980.png)

if i comment @role apps will run but showing this..
3rd problem
![image](https://user-images.githubusercontent.com/10785280/49534365-88beaa80-f8eb-11e8-80e2-79e6b8c6fada.png)

**Comment by nerababo** [comment]
> 1st problem
> ![image](https://user-images.githubusercontent.com/10785280/49534282-5614b200-f8eb-11e8-931f-20a23a934125.png)
> 
> 2nd problem
> ![image](https://user-images.githubusercontent.com/10785280/49534323-6cbb0900-f8eb-11e8-97b7-4307e9206980.png)
> 
> if i comment @ROLE apps will run but showing this..
> 3rd problem
> ![image](https://user-images.githubusercontent.com/10785280/49534365-88beaa80-f8eb-11e8-80e2-79e6b8c6fada.png)

same problems here, twice installed, dev-2-0 is broken!

**Comment by hrshadhin** [comment]
next push will fixed those issue.
