### ISSUE TITLE
After login with demo account (admin,demo123) this error shows up. 

### ISSUE THREAD

**Issue by amran08** [hrshadhin/school-management-system#49]
**for version-2** 
 https://github.com/hrshadhin/school-management-system/tree/v2.0-dev

ErrorException (E_ERROR)
syntax error, unexpected '<', expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) (View: C:\xampp\htdocs\school-management-system\resources\views\backend\partial\leftsidebar.blade.php) (View: C:\xampp\htdocs\school-management-system\resources\views\backend\partial\leftsidebar.blade.php) (View: C:\xampp\htdocs\school-management-system\resources\views\backend\partial\leftsidebar.blade.php)

**Comment by ntn0de** [comment]
same error

**Comment by hrshadhin** [comment]
Please pull latest code and try. I pushed a fixed for this.
