### ISSUE TITLE
Student/Teacher after login issue 

### ISSUE THREAD

**Issue by AhmedEhab95n** [hrshadhin/school-management-system#50]
**Description**
When I login with a student/teacher account I get redirected to admin dashboard and everything gives me error 401 access denied 

**Expected behavior**
A student/teacher should have a different dashboard and other tabs in the right nav bar other than Admin's

**Comment by hrshadhin** [comment]
Please pull latest code right now. 401 issue fixed. 
This project is currently in development dashboard and lots off features are not complete yet!
