### ISSUE TITLE
CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]

### ISSUE THREAD

**Issue by AdittoAbhi** [hrshadhin/school-management-system#54]
Hello Bro,
I'm from bangladesh, so, i think we can talk in bangla.

Bro, Ami apnar fresh School Management System ta install korche, install successful but dashboard e login korley CRV: Application encounted problems ata popup e ase. kivabe solve korbo, full fresh install korche xampp e, laravel 5.6 e. so please help me

**Comment by hrshadhin** [comment]
Thanks for having interest in my project. Check the issue list. Already i answered this question. #29 
If that solutions not work for you, then zip the "resources/views/backend" folder and send me a mail.

As you are a bangladeshi then write either english or pure bangla. Not banglish!

**Comment by armancse** [comment]
CRV: Application encounted problems.Please contact ShanixLab at [hello@hrshadhin.me]  how can solve this .. this error show if i change footer.blade.php some text

**Comment by hrshadhin** [comment]
Why you need to change the footer? is it necessary for you?

**Comment by armancse** [comment]
yes it is  necessary  for me


[image: photograph]
MD Arman Hossain
Web Designer & WordPress Developer
email: armanh522@gmail.com
mobile: + 8801765963902
Bangladesh Skill Development Institute, House 2B, Road # 12 Mirpur Road,
Dhanmondi
[image: facebook icon] <https://www.facebook.com/armantpi> [image: twitter
icon] <https://twitter.com/> [image: youtube icon]
<https://www.youtube.com/> [image: linkedin icon]
<https://www.linkedin.com/in/md-arman-hossain-784aa3144/> [image: google
plus icon] <https://plus.google.com/>  bsdi-bd.org

**Comment by hrshadhin** [comment]
And may i know what is your necessity?

**Comment by armancse** [comment]
just change Developed by ShanixLab <http://shanixlab.com/> this text i
faced one more truble when i want to print upder Reports>Monthly Attendence
then it redirect previous page and not print.. how can solve this >> and
can you help me one this if i want to 4 lavel in attendence like Class,
Section,subject and Teacher wise attendence ..can you do this

[image: photograph]
MD Arman Hossain
Web Designer & WordPress Developer
email: armanh522@gmail.com
mobile: + 8801765963902
Bangladesh Skill Development Institute, House 2B, Road # 12 Mirpur Road,
Dhanmondi
[image: facebook icon] <https://www.facebook.com/armantpi> [image: twitter
icon] <https://twitter.com/> [image: youtube icon]
<https://www.youtube.com/> [image: linkedin icon]
<https://www.linkedin.com/in/md-arman-hossain-784aa3144/> [image: google
plus icon] <https://plus.google.com/>  bsdi-bd.org

**Comment by hrshadhin** [comment]
You are using free(As in freedom)/open source application. And you are not respect it by not giving credit of their works!!!!

**Comment by armancse** [comment]
Thanks for Response i faced one more trouble when i want to print under Reports>Monthly Attendance
then it redirect previous page and not print.. how can solve this >> and
can you help me one this if i want to 4 level in attendance like Class,
Section,subject and Teacher wise attendance ..how can i do
