### ISSUE TITLE
Problem Adding New  Student

### ISSUE THREAD

**Issue by eiadghaith333** [hrshadhin/school-management-system#58]
when trying to add new student i got this error : 

Undefined index: fourth_subject

**Comment by hrshadhin** [comment]
Did you tried lastest commit? which php version did you try?

**Comment by eiadghaith333** [comment]
ok i will tried it than feed back  you :)

**Comment by eiadghaith333** [comment]
ok i will tried it then feed back what happens :)

**Comment by eiadghaith333** [comment]
ok i will try it then feed back what happens :)

**Comment by eiadghaith333** [comment]
i tried it and it has worked fine ,another question is  accounting and fees department  is coming in newest versions?

**Comment by hrshadhin** [comment]
No. Not in this community edition. Those modules are in enterprise edition.
