### ISSUE TITLE
Result module not working 

### ISSUE THREAD

**Issue by hermesk** [hrshadhin/school-management-system#59]
hi, i cannot figure out what is wrong with results module, on opening i get this error

"500
Oops! Something went wrong.
We will work on fixing that right away.
Meanwhile, you may return to home"

**Comment by hrshadhin** [comment]
After installation what did you do exactly. Tell me step by step other wise how could i know what you missed?

**Comment by hermesk** [comment]
i correctly followed your instructions, i was just testing the different modules and on opening the result module that's when i get the error

**Comment by hrshadhin** [comment]
ok, i will check it.

**Comment by hermesk** [comment]
okay

**Comment by woosshie** [comment]
Hello, thanks for your awesome job!!. but I have the same issue. 
[error.log](https://github.com/hrshadhin/school-management-system/files/2974849/error.log)
I hope this could help little to figure out. 
I really wish to have knowledge help.

**Comment by hrshadhin** [comment]
@hermesk pull the latest code and checkit. And when you face issue please set debug true on .env. 
That way you can explain me the proper error.

**Comment by hrshadhin** [comment]
> Hello, thanks for your awesome job!!. but I have the same issue.
> [error.log](https://github.com/hrshadhin/school-management-system/files/2974849/error.log)
> I hope this could help little to figure out.
> I really wish to have knowledge help.

@woosshie its a problem with node. So why are you posting issue on wrong thread!
checkout here #62

**Comment by hermesk** [comment]
> @hermesk pull the latest code and checkit. And when you face issue please set debug true on .env.
> That way you can explain me the proper error.


[error.log](https://github.com/hrshadhin/school-management-system/files/2974955/error.log)

the problem has to do with getting academic year

**Comment by hermesk** [comment]
[result_error.log](https://github.com/hrshadhin/school-management-system/files/2974957/result_error.log)
It has to do with getting the academic years

**Comment by hrshadhin** [comment]
Now i get the proper error report. For school you have to set default academic year from institute settings.

**Comment by hermesk** [comment]
I already tried that. I set default default academic year to 2019 and  I am getting the same error

**Comment by hrshadhin** [comment]
@hermesk Pull the latest code right now. Error will be gone.

**Comment by hermesk** [comment]
@hrshadhin Thank it works
