### ISSUE TITLE
Adding subjects

### ISSUE THREAD

**Issue by zaczx** [hrshadhin/school-management-system#6]
First thanks for the great project its really amazing and again forgive me for raising a functionality question instead of code improvement.
under subject adding there is an option for grade system a drop-down which doesn't pop any detail, could you kindly explain what it is supposed to be.
![subject](https://user-images.githubusercontent.com/2667363/31168669-cf7403aa-a8fe-11e7-9673-219ba2696459.JPG)
Thanks in advance

**Comment by ismaeljoseph** [comment]
Hello, it would be nice to motivate more developer on this project.  If a beginner like me. do you want us to start contributing on it? We will try our best.

**Comment by hrshadhin** [comment]
Thank you, for giving interest in my project. In my country school have two type of grading 100marks and 50 marks. So this dropdown is for grading system.

You can setup up grading from "/gpa" url. Like this one http://school.hrshadhin.me/gpa.

**Comment by zaczx** [comment]
Where i came from, the school year is divided into three parts we call them terms so exams and fees are generated as per term and again a term can have multiple exams eg Opener,midterm and endterm and its the work of the teacher to decide how many marks each term will carry.
and thanks for your response am hoping your project will help me do a system for my local school as a "give back to society initiative"
