### ISSUE TITLE
npm run command error

### ISSUE THREAD

**Issue by hrshadhin** [hrshadhin/school-management-system#62]
Hello, thanks for your awesome job!!. but I have the same issue. 
[error.log](https://github.com/hrshadhin/school-management-system/files/2974849/error.log)
I hope this could help little to figure out. 
I really wish to have knowledge help.

_Originally posted by @woosshie in https://github.com/hrshadhin/school-management-system/issues/59#issuecomment-473620459_

**Comment by hrshadhin** [comment]
Update your node and npm. and reinstall dependency with `npm install`
*Always use node stable version to avoide these type of errors.*

**Comment by hrshadhin** [comment]
@woosshie does your problem solved?

**Comment by woosshie** [comment]
wow thanks for your feed back.

at that time. issue i had was errors when i run

/resources/assets/frontend/css/main.css
there was little Syntax Error.
  2732 | position: absolute;
  2733 | top: -9px;\
> 2734 | left: -webkit-calc(50% - 9px);
       | ^
  2735 | left: -moz-calc(50% - 9px);
  2736 | left: calc(50% - 9px);

after remove " \ " this. no more npm errors but

i am still struggling with

This page isn’t working

*school.test* is currently unable to handle this request.
HTTP ERROR 500

i've tried chmod 755 or 777 folders but still not working so far
if you have some clue please help me out
thanks

**Comment by hrshadhin** [comment]
project is tested on Node v10 and build is fine. I don't know you are getting this. 

> *school.test* is currently unable to handle this request.
HTTP ERROR 500

Set dubug true and checkout error trace.

> i've tried chmod 755 or 777 folders but still not working so far.
On which folder?

**Comment by hrshadhin** [comment]
@woosshie does your problem exists now?
