### ISSUE TITLE
Font awesome icons not showing

### ISSUE THREAD

**Issue by humfricz** [hrshadhin/school-management-system#65]
When i build the app and host it in Xampp i get error 404 for all font icons, but it loads well when i use php artisan serve
![screenshot-localhost-2019 03 25-15-59-11](https://user-images.githubusercontent.com/11071250/54921501-f7fdf000-4f16-11e9-9248-b2d75943468a.png)

**Comment by hrshadhin** [comment]
clear you browser cache first. If problem not gone then check browser console log and paste here.

**Comment by sthaiya** [comment]
Facing same issue. Clearing the cache is not solving it. From the console its trying to look for the fonts and images in the wrong path.

![image](https://user-images.githubusercontent.com/1867808/56461446-f9a6c080-63bb-11e9-9d99-1c15a029a445.png)

**Comment by sthaiya** [comment]
![image](https://user-images.githubusercontent.com/1867808/56461551-928a0b80-63bd-11e9-8ad8-5b3ac88bb91c.png)
