### ISSUE TITLE
Different Menu(s)

### ISSUE THREAD

**Issue by tech-o-neel** [hrshadhin/school-management-system#66]
Most of the menu(s) are missing.
[http://cloudschoolbd.com](http://cloudschoolbd.com)
![image](https://user-images.githubusercontent.com/20424034/55063970-273f6900-509f-11e9-9c5f-7562e56d6b02.png)
[localhost:8000]
![image](https://user-images.githubusercontent.com/20424034/55064052-51912680-509f-11e9-8126-4c4a21858734.png)

[http://cloudschoolbd.com](http://cloudschoolbd.com)
![image](https://user-images.githubusercontent.com/20424034/55063858-ee06f900-509e-11e9-8bc8-529d3758b967.png)

Localhost after Git Clone [all branch]
![image](https://user-images.githubusercontent.com/20424034/55063807-ce6fd080-509e-11e9-81f2-67f53451fa95.png)

**Comment by hrshadhin** [comment]
Yes. [Community Edition](https://sms.hrshadhin.me) and [Enterprise Edition](http://cloudschoolbd.com)
