### ISSUE TITLE
I got error when i try to install on my web hosting

### ISSUE THREAD

**Issue by Abhiana** [hrshadhin/school-management-system#69]
Hello,
Your work is too much good, i had installed on localhost (xampp) successfully without any problem, but when i try to install it on my web hosting then i got error.

here is my error_log content.

`[17-Apr-2019 10:27:48 Asia/Dhaka] PHP Fatal error:  Uncaught Exception: The Mix manifest does not exist. in /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:597
Stack trace:
#0 /home/webhostroot/public_html/storage/framework/views/74d96713fe4d8d771215b16dfb0de32b37f7c76e.php(14): mix('/css/vendor.css')
#1 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/creatprs/...')
#2 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/creatprs/...', Array)
#3 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/creatprs/...', Array)
#4 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View->getContents()
#5 /home/creatprs/public_html/vendor/laravel/framework/src/ in /home/creatprs/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 597`

Please give me the fixing way of this issue.

Thanks.

**Comment by hazhayder** [comment]
If your web hosting provider gave you the access for SSH and NodeJS is installed on the server. Then you can go to the laravel directory and hit npm install after that
npm run backend-prod
 npm run frontend-prod. .
If you don't have that access. Then you need to have that available on the server.
If you need hosting for this please do contact me i'll setup everything for you on my server.

**Comment by Abhiana** [comment]
Hello. i had install nodejs successfully. i had run it on local server xampp. its working but when i try to run it on hosting then its not work. i will buy hosting from you don't worry but i need the host working file first

**Comment by hazhayder** [comment]
> Hello. i had install nodejs successfully. i had run it on local server xampp. its working but when i try to run it on hosting then its not work. i will buy hosting from you don't worry but i need the host working file first

If you want i can setup one for you on the IP you can check it and then buy it so i will put it on your domain.

**Comment by Abhiana** [comment]
Hosting Price?

**Comment by hrshadhin** [comment]
@Abhiana Setup and install all dependecy both npm and composer on local machine.
Then migrate db and seed database. Then export sql file from your phpmyadmin or whatever app you use. Then zip the whole project folder and upload it to your web hosting. extract it. change the settings, import database. point you domain to project folder. Now visit your domain and application will run.

**Comment by hrshadhin** [comment]
> Hello,
> Your work is too much good, i had installed on localhost (xampp) successfully without any problem, but when i try to install it on my web hosting then i got error.
> 
> here is my error_log content.
> 
> `[17-Apr-2019 10:27:48 Asia/Dhaka] PHP Fatal error: Uncaught Exception: The Mix manifest does not exist. in /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:597 Stack trace: #0 /home/webhostroot/public_html/storage/framework/views/74d96713fe4d8d771215b16dfb0de32b37f7c76e.php(14): mix('/css/vendor.css') #1 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/creatprs/...') #2 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/creatprs/...', Array) #3 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/creatprs/...', Array) #4 /home/webhostroot/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View->getContents() #5 /home/creatprs/public_html/vendor/laravel/framework/src/ in /home/creatprs/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 597`
> 
> Please give me the fixing way of this issue.
> 
> Thanks.

@Abhiana Setup and install all dependecy both npm and composer on local machine.
Then migrate db and seed database. Then export sql file from your phpmyadmin or whatever app you use. Then zip the whole project folder and upload it to your web hosting. extract it. change the settings, import database. point you domain to project folder. Now visit your domain and application will run.

**Comment by Abhiana** [comment]
ok bro.

**Comment by hazhayder** [comment]
> Hosting Price?

30$ per year

**Comment by vipulpoonia** [comment]
@abhiana have you installed it on web server. 
Can anyone tell how to install it on shared hosting
