### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gurbhagat** [hrshadhin/school-management-system#7]
kindly add Generate Certificates option
1) transfer certificate
2) character certificate
3) bonafide certificate
please

**Comment by hrshadhin** [comment]
ok. i will think about it. Can u please suggest me about these certificate layout or design.

**Comment by gurbhagat** [comment]
https://www.myclassboard.com/blog/generate-transfer-certificates-school/
sir here is the format there are many other features which you can try
By the way your this project is Superb , Awesome

**Comment by hrshadhin** [comment]
thanks.
