### ISSUE TITLE
Notification url mapping issue

### ISSUE THREAD

**Issue by raaz181** [hrshadhin/school-management-system#74]
i have installed this in subfolder and settled up everything
when we logged in the notification is being querying from root domain not from app path

GET http://example.com/notification/unread?limit=5 404 (Not Found)
it should be
GET http://example.com/sub-folder/notification/unread?limit=5

additionally, please help on this as well, am seeing this almost on every page
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.  (from: pace.js?id=f0c5ee9ee887324c864c:434 )

**Comment by hrshadhin** [comment]
you have to set point your domain to sub-folder. you can use htaccess for that.  Or check how install laravel in subfolder. 

i will check it about pace.js.

**Comment by raaz181** [comment]
> you have to set point your domain to sub-folder. you can use htaccess for that. Or check how install laravel in subfolder.
> 
> i will check it about pace.js.

this is not something about htaccess, the notifications are requested with ajax call from your java script which is not considering the actual public path including subfolder, thats why it returns 404
because of some other reason i can not point example.com directly to subfolder, this is at example.com/subfolder, which should be consider in ajax call
