### ISSUE TITLE
Cache class not included but used in SiteController

### ISSUE THREAD

**Issue by razorsharpshady** [hrshadhin/school-management-system#75]
Cache class is used but not included in the backend/SiteController.php 
Below is the error log, this error is displayed on http://127.0.0.1:8000/site/settings when submitting the form.

``[2019-06-25` 11:54:45] development.ERROR: Class 'App\Http\Controllers\Backend\Cache' not found {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Http\\Controllers\\Backend\\Cache' not found at D:\\school-erp\\school-management-system\\app\\Http\\Controllers\\Backend\\SiteController.php:553)``

I solved this error by including `use \Cache;` in SiteController.

**Comment by hrshadhin** [comment]
Fixed.
