### ISSUE TITLE
font awesome icons not showing,clearing browser cache doesn't help

### ISSUE THREAD

**Issue by matatashadrack** [hrshadhin/school-management-system#76]
Please help,font awesome icons are not showing

**Comment by hrshadhin** [comment]
did you install dependency by `npm install` ?

**Comment by aashu122** [comment]
there is an error 
Failed opening required '/home/ashu/school-management-system/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ashu/school-management-system/artisan on line 18
how i could i fixed it

**Comment by hrshadhin** [comment]
> there is an error
> Failed opening required '/home/ashu/school-management-system/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ashu/school-management-system/artisan on line 18
> how i could i fixed it

May be your dependency not installed. `composer install` first. And your posting your in wrong issue thread!

**Comment by hrshadhin** [comment]
@matatashadrack does your problem resolved?

**Comment by sanal2net** [comment]
I have also not showing font awesome icons. And i install all dependencies. 
Some of the urls are 404 error.
http://localhost/fonts/vendor/font-awesome/fontawesome-webfont.woff?fee66e712a8a08eef5805a46892932ad
http://localhost/fonts/icomoon.woff?f65952a332ed898fb740528af0b6502d

And my project url is **http://localhost/school-management-system/**
![Screenshot_SMS](https://user-images.githubusercontent.com/36921861/61441800-fa6fd400-a963-11e9-9a61-7d8a3caed6e9.png)

**Comment by hrshadhin** [comment]
did you run `npm run backend-prod` command?

**Comment by sanal2net** [comment]
Yes.

**Comment by hrshadhin** [comment]
would you please pull latest code and retry.

**Comment by sanal2net** [comment]
Ok. I will update and let you know. Thanks
