### ISSUE TITLE
SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1 (SQL: insert into

### ISSUE THREAD

**Issue by raaz181** [hrshadhin/school-management-system#81]
SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1 (SQL: insert into `i_classes` (`name`, `numeric_value`, `group`, `order`, `note`, `status`, `updated_by`, `created_by`, `updated_at`, `created_at`) values (One, 1, Science, 1, , 1, 35, 35, 2019-07-05 22:52:15, 2019-07-05 22:52:15))

i dont know whats going wrong here, please help

**Comment by hrshadhin** [comment]
when you face this problem? mention the feature or link.

**Comment by raaz181** [comment]
found the solution, this was because of triggers..

**Comment by vipulpoonia** [comment]
Hey
How to install it in cpanel
