### ISSUE TITLE
Hello, How Do I get the enterprise edition

### ISSUE THREAD

**Issue by Rabach07** [hrshadhin/school-management-system#86]

**Comment by hrshadhin** [comment]
you have to buy it. EE has 2 type of licensing policy. 
1. single domain
2. Resale / Full ownership a copy of code

**Comment by Rabach07** [comment]
can you provide a link to buy?

**Comment by Rabach07** [comment]
I need the resale or full ownership of a copy of the code.

**Comment by hrshadhin** [comment]
please send a mail to hello[at]hrshadhin[dot]me

**Comment by Rabach07** [comment]
sent mail already
