### ISSUE TITLE
Frequent updates, How to manage ?

### ISSUE THREAD

**Issue by raaz181** [hrshadhin/school-management-system#88]
Hi, you are working on this continuously and updating many of scripts or bug fixing, 

can you please help how do i manage updates, because replacing everything every time should not be a solution this lost my all the data every time
how do i know and update every time you update a script on github ?

**Comment by hrshadhin** [comment]
Application database schema is same. There are no changes there. only code bug-fixing and dependency library updates are push. So if you deploy code using git then you can just pull it. Or if you install in c panel and don't have cell access then just pull it locally and upload the zip. 

So no data will loss, it you update the code!

**Comment by raaz181** [comment]
Thanks for quick reply, the problem is i have minor modification in few scripts as required, is there any other way to monitor the only updated files by you and putting them only into action?
