### ISSUE TITLE
Frequent updates - need help on this

### ISSUE THREAD

**Issue by raaz181** [hrshadhin/school-management-system#89]
Thanks for quick reply, the problem is i have minor modification in few scripts as required, is there any other way to monitor the only updated files by you and putting them only into action?

-------------------------
Application database schema is same. There are no changes there. only code bug-fixing and dependency library updates are push. So if you deploy code using git then you can just pull it. Or if you install in c panel and don't have cell access then just pull it locally and upload the zip. 

So no data will loss, if you update the code!

_Originally posted by @hrshadhin in https://github.com/hrshadhin/school-management-system/issues/88#issuecomment-511279098_

**Comment by raaz181** [comment]
@hrshadhin please help on this
also request some help on updating 
to update for latest version do i need to run all the commands of installation after getting new copy from here

**Comment by hrshadhin** [comment]
No. You just have to murge the code.
If update has any dependency update then you have to install them.

Every update just clear the application cache and browser cache also.
