### ISSUE TITLE
Unable to load modules after installation

### ISSUE THREAD

**Issue by swapnilvk** [hrshadhin/school-management-system#91]
I have installed School management system software as per instructions given in repo, but every link shows 401 Access denied page.

I logged in with user: admin
![issue](https://user-images.githubusercontent.com/3316352/61590204-c3ebc080-abd2-11e9-9b25-5134fe78152d.PNG)

**Comment by raaz181** [comment]
it seems you have missed the seeding of database (there is no permissions in your database)

**Comment by swapnilvk** [comment]
> it seems you have missed the seeding of database (there is no permissions in your database)

Thanks for you reply. I have done exact same steps as mentioned in readme file. Still issue is there.

Can you please help me to import database manually.

**Comment by hrshadhin** [comment]
@swapnilvk Did you clear application cache?
