### ISSUE TITLE
Throwing exception during migration in laravel 5.8

### ISSUE THREAD

**Issue by lokibhardwaj** [hrshadhin/school-management-system#92]
@hrshadhin Its throwing exception regarding foreign key constrain during migrations of marks table and results table in Laravel 5.8. Please see following:

Migrating: 2019_02_23_203247_create_marks_table

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Ca
n't create table `school_mgm`.`#sql-165c_147` (errno: 121 "Duplicate key on writ
e or update") (SQL: alter table `marks` add constraint `marks_academic_year_id_f
oreign` foreign key (`academic_year_id`) references `academic_years` (`id`))

    660|         // If an exception occurs when attempting to run a query, we'll
 format the error
    661|         // message to include the bindings with SQL, which will make th
is exception a
    662|         // lot more helpful to the developer instead of just the databa
se's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `s
chool_mgm`.`#sql-165c_147` (errno: 121 "Duplicate key on write or update")")

**Comment by hrshadhin** [comment]
I don't know you are seeing this error. Nobody face that kind or error. Could you please share your 
environments details. like: os, php, mysql version?

**Comment by lokibhardwaj** [comment]
@hrshadhin 
I am using xampp for development on Windows 8.1, following is the development environment detail:

 Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.3.2

**Comment by hrshadhin** [comment]
use mysql version > 5.6

**Comment by lokibhardwaj** [comment]
Alright, let me upgrade.

**Comment by lokibhardwaj** [comment]
After upgrade, its working for me.

Thanks for your help :)

**Comment by vipulpoonia** [comment]
> After upgrade, its working for me.
> 
> Thanks for your help :)

Can you help me out in installing it on cpanel

**Comment by lokibhardwaj** [comment]
@vipulpoonia I have just installed on local for now. I will be able to tell after installation on server.
Thanks

**Comment by vipulpoonia** [comment]
@lokibhardwaj can you mail me zip file of after installation files and database?
