### ISSUE TITLE
A error popup modal appears

### ISSUE THREAD

**Issue by tsheringdendu** [hrshadhin/school-management-system#95]
a pop up modal in user dashboard saying "CRV: Application encounted problems.Please contact ShanixLab[hello@hrshadhin.me]" appears.   
![error](https://user-images.githubusercontent.com/39291087/63744898-87427180-c8c2-11e9-92e3-430db46381d6.jpg)

**Comment by hrshadhin** [comment]
Follow issue no #29 . Before create an issue please search in previous issue list.
