### ISSUE TITLE
CRV: Application encounted problems.Please contact ShanixLab[hello@hrshadhin.me]

### ISSUE THREAD

**Issue by DrTridz** [hrshadhin/school-management-system#96]
i looked for a solution to the following problem
`CRV: Application encounted problems.Please contact ShanixLab[hello@hrshadhin.me]
`
as the picture

![1](https://user-images.githubusercontent.com/23523041/63780893-8a088b00-c8f1-11e9-8a1f-86e44c52616c.png)

--------------------------------------
other issues were looked at in the same problem, including:
https://github.com/hrshadhin/school-management-system/issues/54
&
https://github.com/hrshadhin/school-management-system/issues/34

-------------------------------------
i deleted and reinstalled the project and it didn't work and i downloaded the project more than once and it didn't work

does the project run on a local Windows host such as xampp or wamp..?
or just works on Linux..?

i hope you, my friend, tell me a solution to the problem
Thank you

**Comment by DrTridz** [comment]
I know the questions about
[https://github.com/hrshadhin/school-management-system/issues/29](url)
It may bother you and I am sorry but I hope it will help me

**Comment by DrTridz** [comment]
sorry and i have problem in Site->Dashboard->Google Analytics Report
 (Google json key file missing!)

Thank you Thank you Thank you

**Comment by hrshadhin** [comment]
Does your problem solved?

**Comment by DrTridz** [comment]
Yes, the problem stopped when Google Chrome's automatic translator was turned off

**Comment by hrshadhin** [comment]
ok. i'm closing this issue.

**Comment by hrshadhin** [comment]
Hi guys, found a problem.
If you are using windows and use git clone for download the code then first run these commands:
```bash
git config --global core.eol lf
git config --global core.autocrlf false
```
OR down the code from direct link: [here](https://github.com/hrshadhin/school-management-system/archive/master.zip)
