### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by smanojsrinivasan** [hrshadhin/school-management-system#99]
Can we have steps to install on windows

**Comment by b4oshany** [comment]
### For Windows:

- Install WAMP or XAMPP
- Install Composer for Windwos
- Install NodeJS and NPM
- Ensure that Composer and PHP are in your environmental path
- Open the cmd via WAMP or XAMPP
- Run `composer install`
- Run `npm install`
- Run `npm backend-prod`
- Run `npm frontend-prod`
